# resources:
#   - name: git
#     type: GitRepo
#     configuration:
#       path: bharath92/sample-runSh
#       gitProvider: github
#       branches:
#         include: master 

pipelines:
  - name: basic1
    steps:
      - name: basic
        type: Bash
        configuration:
          affinityGroup: basic_group
          runtime:
            type: host
# #           inputResources:
# #            - name: git
#           environmentVariables:
#             foo: bar
#           runtime:
#             type: host
        execution:
          onExecute:
            - printenv
            - sleep 2m
            - add_pipeline_variables foo=bar
            - echo loool
      - name: basic2
        type: Bash
        configuration:
          affinityGroup: basic_group
          runtime:
            type: host
          inputSteps:
            - name: basic
        execution:
          onExecute:
            - printenv
            - sleep 2m
            - add_pipeline_variables foo=bar
            - echo loool
#       - name: second
#         type: Bash
#         configuration:
#           #inputResources:
#           #  - name: git
#           environmentVariables:
#             foo: bar
#           runtime:
#             type: host
#         execution: 
#           onExecute:
#             - echo $foo
#       - name: third
#         type: Bash
#         configuration:
#           #inputResources:
#           #  - name: git
#           inputSteps:
#             - name: basic
#             - name: second
#           environmentVariables:
#             foo: bar
#           runtime:
#             type: host
#         execution:
#           onExecute:
#             - echo $foo
          
